version: '2'

services:

  export:
    build:
      context: .
      dockerfile: Dockerfile.export
    volumes:
      - ".:/usr/src/app"
    links:
      - es
    env_file:
      - .env_default
      - .env

  import:
    build:
      context: .
      dockerfile: Dockerfile.import
    volumes:
      - ".:/usr/src/app"
    links:
      - es
    env_file:
      - .env_default
      - .env

  fill:
    build:
      context: .
      dockerfile: Dockerfile.import
    command: ruby fill.rb
    volumes:
      - ".:/usr/src/app"
    links:
      - es
    env_file:
      - .env_default
      - .env

  es:
    image: elasticsearch
